# Generated by Django 5.1 on 2024-09-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='number_of_projects',
            new_name='number_of_project',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='historical_performance_data',
            field=models.FloatField(default=0.0),
        ),
    ]
